### ISSUE TITLE
Add email to alert users

### ISSUE THREAD

**Issue by brothman01** [CodeParrots/php-notifier#1]
When the version of PHP used on the site is soon to be deprecated an email should be sent to Admins with the version of PHP being used and the date that it will no longer be supported.

**Comment by EvanHerman** [comment]
@brothman01 

Email frequency will be controlled via the settings page. Still not sure that a settings page is needed, but it's there - so we may as well run with it.

However, when a PHP version is soon to be deprecated or becomes deprecated an email should definitly be sent letting the site admins know. 

I'm not sure an email continuously letting them know what versionf of PHP the site is running is really useful, and would get annoying quickly. I see the benefit in emails about soon to be deprecated and/or fully deprecated versions.

Emails will also need to be setup to run via cron depending on the frequency set by the user.

______________________________

#### Important:
- [ ] As of 1.29.2017 the emails are sent when the user has the 'Send Email' option checked off and updates the option page.

**Comment by brothman01** [comment]
I'll make sending the email a cron task that is only sent however often the user specifies.
