### ISSUE TITLE
Dismissible notices

### ISSUE THREAD

**Issue by EvanHerman** [CodeParrots/php-notifier#10]
I'm wondering if the notices should be dismissable or not.

Maybe the deprecated notices cannot be dismissed, whereas the 'Deprecated Soon' messages can be. Once dismissed they wouldn't display until the PHP version is fully deprecated.

**Comment by brothman01** [comment]
Add alerts to dashboard based on warning type that have the following attributes:

Unsupported:
Not dismissible, red border alert on dashboard

Deprecated:
Not dismissible, red border alert on dashboard

Deprecated Soon:
Dismissible, red border alert on dashboard

Supported/ running supported version:
No alert on dashboard

**Comment by brothman01** [comment]
done

**Comment by EvanHerman** [comment]
This is not done. Adding a dismissible class to the container does not make the container dismissible. 

Refreshing the page forces the notice to display again. This needs to be rolled back and re-addressed.

**Comment by brothman01** [comment]
tested and dismissed notice is back on refresh

**Comment by EvanHerman** [comment]
Resolved across all branches.
