### ISSUE TITLE
add dashboard widget to let user know if PHP is up to date

### ISSUE THREAD

**Issue by brothman01** [CodeParrots/php-notifier#3]

**Comment by brothman01** [comment]
evan added a footer thing instead, @EvanHerman should we have an option to disable that?

**Comment by EvanHerman** [comment]
@brothman01 We have already included an option to disable it. See https://github.com/CodeParrots/php-notifier/blob/master/README.md

```php
/**
 * Turn off the admin footer text
 */
add_filter( 'php_notifier_admin_footer_text', '__return_false' );
```

**Comment by brothman01** [comment]
yeah,  The version in the footer of the dashboard is enough, nevermind this feature.
